### ISSUE TITLE
When Show in modal

### ISSUE THREAD

**Issue by creativefull** [istvan-ujjmeszaros/bootstrap-colorpickersliders#12]
When I Use in modal bootstrap i can't select the color ,
maybe position z-index less than modal bootstrap

**Comment by astercraker** [comment]
I solution this problem with this:
.cp-popover-container{
         z-index:10000;
     }
    .popover{
        z-index:10000;
    }
one of this work

**Comment by creativefull** [comment]
ok thnk's :)
